name: Build and Create Draft Release

on:
  push:
    branches:
      - main
      - gh_actions

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Prepare environment
        run: |
          uv lock

      - name: Build package
        run: |
          uv build
          ls -la dist/

      - name: Create Draft Release
        uses: softprops/action-gh-release@v1
        with:
          body: "Draft release"
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          prerelease: true
          files: |
            LICENSE
            dist/*.whl
            dist/*.tar.gz
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}